homeassistant:
  name: BRUH3
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include misc/customize.yaml

frontend:

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  server_port: !secret server_port
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  use_x_forwarded_for: True
  trusted_networks:
    - !secret trusted_ip
    - !secret trusted_ip_2
  ip_ban_enabled: True
  login_attempts_threshold: 5

alarm_control_panel:
  - platform: manual

config:

conversation:

device_tracker:
  - platform: owntracks
  - platform: locative
  - platform: nmap_tracker
    hosts: !secret nmap_ip
  - platform: netgear
    host: !secret router_IP
    username: !secret router_account
    password: !secret router_password
    port: !secret router_port

discovery:

history:

logbook:

logger:
  default: info

media_player:
  - platform: cast
  - platform: kodi
    host: !secret kodi_ip

mqtt:
  broker: !secret mqtt_broker_ip
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

notify:
  - name: ecobee
    platform: ecobee
  - name: ben
    platform: html5
    gcm_api_key: !secret ben_gcm_api_key
    gcm_sender_id: !secret ben_gcm_sender_id

panel_iframe:
  configurator:
    title: Editor
    icon: mdi:wrench
    url: https://hassbian.local:3218

recorder:
  purge_days: 7
  
sun:

updater:

tts:
  - platform: google

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
  device_config: !include zwave_device_config.yaml

#### Not in Use Because of HTTPS
##panel_iframe:
##  octoprint:
##    title: 'OctoPrint'
##    url: !secret octoprint_ip_https
##    icon: mdi:printer-3d
##  router:
##    title: 'Router'
##    url: !secret router_ip_https
##    icon: mdi:router-wireless

###########INCLUDES#####
alert: !include_dir_merge_named alerts/
automation: !include automations.yaml
cover: !include_dir_list covers/
input_boolean: !include misc/input_boolean.yaml
input_select: !include misc/input_select.yaml
input_slider: !include misc/input_slider.yaml
binary_sensor: !include_dir_list binary_sensors/
sensor: !include_dir_list sensors/
light: !include_dir_list lights/
shell_command: !include misc/shell_commands.yaml
switch: !include_dir_list switches/
script: !include_dir_merge_named scripts/
group: !include groups.yaml
weather: !include_dir_list weather/
weblink: !include misc/weblinks.yaml
zone: !include_dir_list zones/
camera: !include_dir_list cameras/

##########OTHER#####

android_ip_webcam:
  # This should be the ip of your phone
  - host: !secret B6P_ip
    name: B6P
    username: !secret B6P_username
    password: !secret B6P_password

arlo:
  username: !secret arlo_email
  password: !secret arlo_password
  
ecobee:
  api_key: !secret ecobee_api

emulated_hue:
  type: google_home
  listen_port: 80
  host_ip: !secret pi_ip
  expose_by_default: true
  exposed_domains:
    - cover
    - fan
    - light
    - switch

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

hdmi_cec:
  platform: media_player
  devices:
    1: TV
    2:
      1: Chromecast
      2: KODI
      3: HA
      4: PC

ifttt:
  key: !secret ifttt_api

#image_processing:
#  - platform: dlib_face_detect
#    source:
#     - entity_id: camera.octoprint

octoprint:
  host: !secret octoprint_ip
  api_key: !secret octoprint_api