alias: "Late Night"
initial_state: True
hide_entity: False
trigger:
  platform: time
  after: '22:00:00'
# condition:
  # - condition: state
    # entity_id: group.all_devices
    # state: "home"
action:
  - service: light.turn_on
    data:
      entity_id:
       - light.front_door_right
       - light.front_door_left
       - light.back_door
      brightness: 50
      color_temp: 287
      rgb_color: [255,255,255]
      transition: 30