alias: "Sunrise"
initial_state: True
hide_entity: False
trigger:
  platform: sun
  event: sunrise
# condition:
  # - condition: state
    # entity_id: group.all_devices
    # state: "home"
action:
  - service: light.turn_off
    data:
      entity_id:
       - light.front_door_right
       - light.front_door_left
       - light.back_door
      transition: 30