alias: "Sunset"
initial_state: True
hide_entity: False
trigger:
  platform: sun
  event: sunset
  offset: "-1:00:00"
# condition:
  # - condition: state
    # entity_id: group.all_devices
    # state: "home"
action:
  - service: light.turn_on
    data:
      entity_id:
       - light.switch
       - light.wall
       - light.sink
       - light.front_door_right
       - light.front_door_left
       - light.back_door
       - light.floor_lamp
      brightness: 255
      color_temp: 196
      rgb_color: [255,255,255]
      transition: 300
  - service: light.turn_on
    data:
      entity_id:
       - light.front_door_right
       - light.front_door_left
       - light.back_door
      brightness: 195
      color_temp: 300
      rgb_color: [255,255,255]
      transition: 300