alias: "Sunrise"
initial_state: False
hide_entity: False
trigger:
  - platform: time
    after: '22:00:00'
# condition:
  # - condition: state
    # entity_id: group.all_devices
    # state: "home"
action:
  - service: light.turn_off
    data:
      entity_id:
       - light.switch
       - light.wall
       - light.sink
       - light.floor_lamp
      transition: 30