alias: "motion activated lights while sleeping mode is enabled"
initial_state: True
hide_entity: False
trigger:
  - platform: state
    entity_id: sensor.aeotec_multisensor_6_motion_template
    state: "motion detected"
  - platform: state
    entity_id: sensor.fibaro_motion_template
    state: "motion detected"
  - platform: state
    entity_id: binary_sensor.kitchen_occupancy
    state: "On"
  - platform: state
    entity_id: binary_sensor.main_floor_occupancy
    state: "On"
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: template
    value_template: "{% if states('input_select.ben_status') == 'Sleeping' or states('input_select.cailin_status') == 'Sleeping' and now.hour <= 6 %} true {% elif states('input_select.ben_status') == 'Sleeping' and states('input_select.cailin_status') == 'Sleeping' %}true{% else %}false{% endif %}"
  - condition: state
    entity_id: input_boolean.motion_lockout
    state: "off"
action:
  service: script.motion_sleeping_night