alias: "Porch Input Effect"
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: input_select.porch_led_effect
action:
  - service: mqtt.publish
    data_template:
      topic: "bruh/mqttstrip/seteffect"
      payload: '{{ trigger.to_state.state | string }}'