alias: Media Stopped Night
initial_state: True
hide_entity: True
trigger:
  - platform: state
    entity_id: media_player.living_room
    state: "off"
action:
  - service: light.turn_on
    data:
      entity_id:
       - light.switch
       - light.wall
       - light.sink
      brightness: 255
      color_temp: 200
      rgb_color: [255,255,255]
      transition: 15